FROM openjdk
WORKDIR usr/lib
ADD ./target/UserAuthenticationServices-0.0.1-SNAPSHOT.jar /usr/lib/UserAuthenticationServices-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","UserAuthenticationServices-0.0.1-SNAPSHOT.jar"]
