version: "3.9"
services:
  authService:
    image: auth-app-image
    build: AuthApp/
    container_name: auth-app-container
    ports:
      - 4444:4444
    networks:
      - microserviceNetwork
    depends_on:
      - mysqlService
      - apigateway
      - discovery-server
    restart: always

  mysqlService:
    image: mysql
    container_name: mysql-cont
    ports:
      - 3306:3306
    networks:
      - microserviceNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always

  userproductService:
    image: user-product-image
    build: UserProductApp/
    container_name: user-prod-cont
    ports:
      - 5555:5555
    networks:
      - microserviceNetwork
    depends_on:
      - mongoService
      - apigateway
      - discovery-server

  mongoService:
    image: mongo
    container_name: mongo-cont
    ports:
      - 27017:27017
    networks:
      - microserviceNetwork

  apigateway:
    container_name: spring-cloud-api-gateway
    build: Apigateway/
    networks:
      - microserviceNetwork
    ports:
      - 9998:9998

  discovery-server:
    container_name: spring-cloud-discovery-service
    build: discovery-server/
    networks:
      - microserviceNetwork
    ports:
      - 8761:8761

networks:
  microserviceNetwork:
    driver: bridge