version: "3.9"
services:
  authService:
    image: auth-app-image
    build: UserAuthApp/
    container_name: auth-app-container
    ports:
      - 4444:4444
    networks:
        - microserviceNetwork
    depends_on:
        - mysqlService
    restart: always

  mysqlService:
    image: mysql
    container_name: mysql-container
    ports:
      - 3306:3306
    networks:
        - microserviceNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always

  userTrackService:
    image: user-product-image
    build: UserTrack/
    container_name: user-Track-container
    ports:
     - "5555:5555"
    networks:
     - microserviceNetwork
    depends_on:
     - mongoService

  mongoService:
    image: mongo
    container_name: mongo-container
    ports:
      - 27017:27017
    networks:
      - microserviceNetwork
networks:
  microserviceNetwork:
    driver: bridge