version: '3.9'
services:
  track-service:
    image: track_image
    container_name: track-service
    build: UserTrackService/
    restart: always
    networks:
      - microserviceNetwork
    ports:
      - 8081:8081
    depends_on:
      - mongoService
      - apigateway
      - eureka-service


  mongoService:
    image: mongo
    container_name: mongoService
    ports:
      - 27017:27017
    networks:
      - microserviceNetwork

  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: UserAuthenticationService/
    restart: always
    networks:
      - microserviceNetwork
    ports:
      - 8084:8084
    depends_on:
      - mysqlService
      - apigateway
      - eureka-service


  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    networks:
      - microserviceNetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  apigateway:
    container_name: apigateway
    build: SpringApiGateway/
    networks:
      - microserviceNetwork
    ports:
      - 9100:9100
    depends_on:
      - eureka-service

  eureka-service:
    container_name: eureka-service
    build: MusicEurekaServer/
    restart: always
    networks:
      - microserviceNetwork
    ports:
      - 8761:8761



networks:
  microserviceNetwork:
    driver: bridge