version: "3.9"
services:
  mysql-user-service:
    image: mysql:latest
    ports:
      - "3307:3307"
    container_name: mysql-container
    networks:
      - user-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always

  user-authentication-service:
    container_name: user-authentication-service
    build: ./
    networks:
      - user-net
    ports:
      - "8082:8082"
    depends_on:
      - mysql-user-service
    restart: always
networks:
  user-net:
    driver: bridge

